### ISSUE TITLE
why "mix firmware" calls docker ?

### ISSUE THREAD

**Issue by ramstein74** [nerves-project/nerves#186]
![image](https://user-images.githubusercontent.com/1210858/29466331-6b3fc8c2-8434-11e7-82b0-936a9eb71084.png)

help please ?

**Comment by mobileoverlord** [comment]
The reason it is failing there is because it was trying to download a toolchain for the `win` platform which we do not currently have support for. There is experimental support for windows while running under the windows subsystem for linux. 

You can find more info on enabling this here: https://msdn.microsoft.com/en-us/commandline/wsl/install_guide

**Comment by ramstein74** [comment]
ok. so i will try on linux
Thank you

2017-08-18 16:47 GMT+01:00 Justin Schneck <notifications@github.com>:
