### ISSUE TITLE
Nerves.Bootstrap.Aliases prevents loading target code needed for :debugger

### ISSUE THREAD

**Issue by tiger808** [nerves-project/nerves#301]
### Environment

* Erlang version (`erl -eval 'erlang:display(erlang:system_info(otp_release)), halt().'  -noshell`): 21
* Elixir version (`elixir -v`): Elixir 1.6.6 (compiled with OTP 19)
* Operating system: Mac OS 10.13.6
* Nerves Environment Info:
  (`mix nerves.env --info`) or
  General info about target / system / toolchain
tab$ mix nerves.env --info
warning: String.strip/1 is deprecated, use String.trim/1
  /Users/tab/Documents/Elixir/gizmo/firmware/deps/rpi3/poison/mix.exs:4

|nerves_bootstrap| Environment Package List

  Pkg:         nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:         1.0.0
  Type:        toolchain
  BuildRunner: {Nerves.Artifact.BuildRunners.Local, []}

  Pkg:         nerves_toolchain_ctng
  Vsn:         1.4.0
  Type:        toolchain_platform
  BuildRunner: nil

  Pkg:         nerves_system_rpi3
  Vsn:         1.2.1
  Type:        system
  BuildRunner: {Nerves.Artifact.BuildRunners.Docker, []}

  Pkg:         nerves_system_br
  Vsn:         1.3.2
  Type:        system_platform
  BuildRunner: nil

|nerves_bootstrap| Loadpaths Start

Nerves environment
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

|nerves_bootstrap| Environment Variable List
  target:     rpi3
  toolchain:  /Users/tab/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-darwin_x86_64-1.0.0
  system:     /Users/tab/.nerves/artifacts/nerves_system_rpi3-portable-1.2.1
  app:        /Users/tab/Documents/Elixir/gizmo/firmware

|nerves_bootstrap| Loadpaths End

### Current behavior

```
iex --name myHost@127.0.0.1 --cookie shared_secret -e "Node.connect(:'gizmo@gizmo.local')" -S mix run --no-start
Erlang/OTP 21 [erts-10.0.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

** (Mix) You are trying to run code compiled for rpi3
on your host. Please unset MIX_TARGET to run in host mode.
```

The check is in Nerves.Bootstrap.Aliases.run/1
Commenting out the check does let one get into IEX, but then I still am having trouble getting `int.ni(MyModule) to work. It fails with:
```
** Invalid beam file or no abstract code: "/path/to/my-module.ex"
```

### Expected behavior

The current behavior is reasonable and a good guardrail. We need an enhancement to allow target code to be interpreted for :debugger on the host when remote debugging the target. Something like a --force option that overrides the target check, and perhaps enforces --no-start if the target isn't host.

**CAVEAT:** I don't know if this is a regression. I have not gotten :debugger to interpret any module yet. I was working off this blog post from 2017/11/22:
https://crypt.codemancers.com/posts/2017-11-22-elixir-remote-debugging/
But it seems that Emil Soman had it working last year.

**Comment by ConnorRigby** [comment]
So i don't think this will be limited to just aliases. There is a lot going on here. I don't know quite enough about remote debugging to say for sure, but i suspect this will need to work similarly to `:observer` to work correctly. 

When doing `iex --name myHost@127.0.0.1 --cookie shared_secret -e "Node.connect(:'gizmo@gizmo.local')" -S mix run --no-start` (assuming you have `MIX_TARGET=rpi3` in your environment can not work at all, since erts, all the beam files, any C code is all cross compiled for your device. You  may be able to get this to work _without_ that env var similarly to  how we setup `:observer`. I will try a few things out and report back when i know more.

**Comment by tiger808** [comment]
Thanks @ConnorRigby. I'm trying to debug some target specific code (which of course can't run on host). Do you think that it makes sense to put that module in my `deps(host)` and compile with `MIX_TARGET=host` so that I can get the abstract code interpreted locally but not run?

:observer works great for me. Interestingly I can run it on the target via `--remsh` and see the gui locally. But the same trick doesn't work with :debugger because of wx dependencies which are not built into the target. So does :observer not use wx but :debugger does?

**Comment by ConnorRigby** [comment]
I was just able to connect a remote debugger to my running nerves device. The issue is as you've noticed with target code. (i was using `nerves_network` for example. I'm not exactly sure of the best way to handle this. Does the code in the debugger run on the remote node or local node? If it is the first option, all we need is to ensure the beam files are loaded, but not executable. Not 100% sure how to handle this. I will keep poking around and see what i can come up with

**Comment by ConnorRigby** [comment]
okay i found a workaround:
make a file called `mix.tasks.nerves.debugger.ex` and add this to it:
```
defmodule Mix.Tasks.Nerves.Debugger do
  use Mix.Task

  def run([]) do
    {:ok, _} = Node.start(:"console@192.168.1.106")
    Node.set_cookie(:"oV5urlARgSj3jJi6DDW0T6+RQZVL7GlEZUH6N+SIRYLek+Eblgbcur/2gM/XEYR6")
    true = Node.connect(:"hello_nerves@192.168.1.138")
    :debugger.start()

    :int.ni(Nerves.Network)
    blah()
  end

  defp blah do
    Process.sleep(100)
    blah()
  end
end

```

Then from your shell do: `env MIX_TARGET=rpi3 mix nerves.debugger`

obviously this is a hack, but it's something we can possibly add to `nerves_init_gadget` or something along those lines once refactored

**Comment by tiger808** [comment]
How did you do it? Are you running the debugger on the remote node? Does that node have wx baked in?(which system?) Or did you do it with debugger running on the local host attached to the remote?

I've tried both options. Either option is fine for me, but I don't need wx on the device, and that path led me to needing to build a custom system which I'm not ready to learn yet while frying other fish. And all other things being equal, I'd rather run the debugger somewhere besides on the node being debugged.

**Comment by ConnorRigby** [comment]
yeah `:wx` does _not_ support cross compilation, so that route is pretty much a no go.

I just ran `mix nerves.new hello_nerves`, then brought up network, epmd, and then did `Node.start(name)`

then from the shell you can do 
`iex --name console@localhost --cookie "oV5urlARgSj3jJi6DDW0T6+RQZVL7GlEZUH6N+SIRYLek+Eblgbcur/2gM/XEYR6" -S mix --no-start` 
and connect everything up and run  `:debugger.start()`.

**Comment by tiger808** [comment]
Oops. Messages crossed. I'll take it for a spin. Thanks!

**Comment by ConnorRigby** [comment]
Good luck. I'm going to think on this a bit, but i will likely move this issue to https://github.com/Nerves-Project/nerves_init_gadget tomorrow, since this is more of a runtime/platform specific issue.

**Comment by mobileoverlord** [comment]
This is supported with Elixir ~> 1.9 by setting `preferred_cli_target: [run: :host, test: :host]` in your mix file's `project/0` config.
