### ISSUE TITLE
Docs for Phoenix Web Interfaces outdated and/or erroneous

### ISSUE THREAD

**Issue by odiumediae** [nerves-project/nerves#304]
I'm trying to learn Nerves for a personal project and unfortunately the docs are giving me a hard time, because they are a mess. I'd love to contribute and make them better, but without the docs I pretty much cannot use and learn Nerves to improve the docs in the first place. There are some resources on the web, but they are either chaotic, outdated or awful as well.

That being said, as unproductive as it may be, I'd like to use Nerves with the Phoenix Framework. I went through the `Phoenix Web Interfaces` section of the docs several times, but I'm getting thrown error messages in my face en masse and half of them don't even make any sense.

I suspect it's because there were some mix ups with the new (>= 1.3) and the old (< 1.3) Phoenix, because the docs mention both, `mix phx` and `mix phoenix` and however I follow the docs (poncho or umbrella, `mix.phx` or `mix.phoenix`), I'm getting loads of cryptic errors and nothing works as expected.

I was using asdf and the versions of Erlang (20.2) and Elixir (1.6.2) as mentioned in the docs at first, except I had to update Erlang to 21.0, even though the docs still call for Erlang 20.2. The Nerves example with Phoenix is also still using Phoenix 1.2, so no dice either.

I'd greatly appreciate, if somebody would go over the docs and its contained tutorials and cross-check/repair them, so people who are, like me, new to Nerves and/or as stupid as me could also be up by default for a nice experience of learning Nerves.

**Comment by pdgonzalez872** [comment]
Hi @odiumediae. I played around with Nerves + Phoenix this past week/weekend and was able to get a little UI that allows you to click a `turn on` and `turn off` link which successfully turns an LED on and off.

I have not put together a write up or written any documentation on it yet. Let me know if there is interest and I'll add it to my list.

Here is the repo: https://github.com/pdgonzalez872/nerves_gpio. My target was an `rpi3`.

I went through tutorials of each of the libs I tried to use, mainly copying/pasting code until I got something working and then moving forward to the next step.

I don't know how much detail I should give here, because I don't want to skip steps (which I believe is a reason you created this issue, the steps may or may not add up). The gist of the steps for me was the following:

- create a folder for your project. Inside that folder, create a vanilla nerves project. Get wifi working on it so you can push updates to device over the air.
- create a phoenix app, place it beside the nerves app. Then, on the nerves app create a dependency to the phoenix app `https://github.com/pdgonzalez872/nerves_gpio/blob/master/nerves_basic_skeleton/mix.exs#L53`
- After talking to @mobileoverlord about architecture, he suggested creating a different app to do any logic work in between the nerves and phoenix apps. I called this intermediate app `InBetween`. Which, in hindsight, is not really that great of a name, because of where the dependency ends up defined: In the [phoenix app](https://github.com/pdgonzalez872/nerves_gpio/blob/master/ui/mix.exs#L41)
- Once the nerves device boots up, you can visit it's `ip` address with a browser and see the phoenix app loaded. You may need to hit `:4000`, not sure how you have your router configured, I did some rerouting on mine.

Regardless, you should be using some type of debugging technique. Either an `hdmi` cable connected to a monitor or a [UART cable (cc @ConnorRigby, thank you)](https://www.adafruit.com/product/954?gclid=EAIaIQobChMIuv2LucLO3AIVicJkCh2GiQXrEAQYASABEgLyl_D_BwE) interfacing with `screen`. The latter is most efficient in my opinion and a very helpful step to achieve sanity.

Please let me know if this helps at all.

Here is a gif of the project:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/8906358/43589322-103dcdc6-9634-11e8-90c2-176ce7e39deb.gif)

**Comment by odiumediae** [comment]
@pdgonzalez872 Thank you very much for your great, detailed response – that helps a lot! And as for the documentation, good code is all the documentation I need.

I can see better what I did wrong now in regard to the config files.

I'm using a Raspberry Pi 2 Model B, Rev. 2 and a Raspberry Pi Zero W, but those should both work more or less the same, since it's mainly a matter of configuration.

I'll snoop through your repo and report what I've learned and what exactly I did wrong afterwards, so that others may learn from your help and what I've learned.

Thanks again! <3

**Comment by odiumediae** [comment]
Whatever I do, I cannot run `mix firmware` successfully. It always gives me the following error message:

```
could not compile dependency :ui, "mix compile" failed. You can recompile this dependency with "mix deps.compile ui", update it with "mix deps.update ui" or clean it with "mix deps.clean ui"
```

If I'm not mistaken, this has something to do with `export MIX_TARGET=rpi2`, but even if I reset it with `export MIX_TAGRET=host`, delete the deps and _build folders, lockfiles and retry, I get the same errors.

Am I misunderstanding or forgetting something here?

**Comment by odiumediae** [comment]
Now I'm getting ```
==> Failed to load config:
    could not load release config rel/config.exs
    ** (UndefinedFunctionError) function Mix.Config.Agent.start_link/0 is undefined (module Mix.Config.Agent is not available)
```

Even though I ran `mix nerves.release.init` after I got that error the first time.

I don't know what it is, maybe my setup, but something is missing, configured wrong or just buggy and I can't find the problem.

**Comment by pdgonzalez872** [comment]
So I'm not sure which repo you are using, but if you are using mine you can check https://github.com/pdgonzalez872/nerves_gpio/blob/master/nerves_basic_skeleton/mix.exs#L57-L58 and see that it is configured for the `rpi3`. Let me see if I can put together something that would "just work". If I don't get to it today, I suggest you start small at first and build upon a project. If you have done this already, I'd suggest using the project that worked before and following the docs to get the UI going.

If you haven't, I'd focus on using the `rpi0` you have and connecting it successfully to the wifi. I wrote a blog post that touches on that. Here is the [link](https://medium.com/@pdgonzalez872/using-nerves-with-rpi3-wifi-and-picam-3b04cee78d22) to it.

Once it is on the wifi, add the UI portion to it. Here are the docs for it: https://hexdocs.pm/nerves/user-interfaces.html#choosing-a-project-structure

You make a good point with the need for docs/guides. I'd probably prefer to revamp the docs and make sure those are up to date. Unfortunately there are lots, lots of moving pieces in the nerves ecosystem and examples can get stale. Elixir moves forward, other libs do too, Erlang, OTP, everything, haha, it's awesome that things move forward, but hard to keep up the tutorials going.

As I said earlier, I think the best tutorial for Nerves and learning the ecosystem is to start from the first example and move upwards. Mainly because once you have some things set up (wifi for example) you can do so much to add to a project. The same project can have a webcam, a ui, and many other applications running at the same time. Also, once you have the wifi configured, you can push updates with `mix firmware.push` and that's a game changer in my opinion...

If it helps you, create a repo and start pushing to it. If you have done so already, please link it here.

Hope this helps! PD

**Comment by mobileoverlord** [comment]
Looks like you’re using elixir 1.7. Nerves doesn’t support 1.7 yet. I’ll be posting a release candidate today to add support, but ultimately we have to wait until distillery releases 2.0

**Comment by odiumediae** [comment]
@pdgonzalez872 Hey, thanks again, for your help. I've read the blog post and learned a few details that'll help later, but for now the problem was differing versions, as @mobileoverlord correctly assumed.

The docs tell you to use Erlanf/OTP 20.2 and Elixir 1.6.2., but when I used Erlang OTP 20.2, I got an error that told me to use Erlang/OTP 21.0 and so after lots of other interchanging errors that didn't made too much sense for me, I tried Elixir 1.7.1. I just assumed that the docs might also be outdated on that, but I didn't know that Elixir 1.7 wasn't supported yet, due to the distillery dependency.  I also forgot doing `mix do local.hex, local.rebar` between changing the Erlang and Elixir versions which made things a lot more complicated an error prone.

I couldn't run your project, @pdgonzalez872, because I don't have part of the hardware (breadboard, LED, etc), so I read through the source and tried my luck where I wasn't already sure what to do. That helped a lot, but the differing versions made it complicated.

I'll submit a pull request today that changes nerves docs to reflect the correct versions and when I got my project running, I'm going to publish a blog post about it that clears up some of the pitfalls I fell into.

Thank you both for you help!

**Comment by odiumediae** [comment]
Oh, it's already done, thanks @fhunleth! I'm gonna close this.

**Comment by pdgonzalez872** [comment]
@fhunleth and @odiumediae I wrote this: https://github.com/nerves-project/nerves_examples/pull/91 and have tested it on a `rpi0w`.

![image](https://user-images.githubusercontent.com/8906358/43680806-4fcd0300-9808-11e8-850a-681c6d88bbae.png)

Remember to pass in the wifi name and password when launching the commands:
https://github.com/nerves-project/nerves_examples/pull/91/commits/fa69a3a1fab4f4df0d9d08b7f7d63efde0191538

You set the mdns here (In our case, I chose `nerves_base.local`):
https://github.com/nerves-project/nerves_examples/pull/91/files#diff-387c4a65a44daad46e303dd94697931fR21

Please let me know if this is what you had in mind as working example. Hope you get it working soon. PD
