### ISSUE TITLE
nerves_bootstrap archive should be publicly versioned

### ISSUE THREAD

**Issue by ghitchens** [nerves-project/nerves#71]
I experienced a problem where nerves_bootstrap was out of date, but I had no way of diagnosing it.  Updating it via mix local.nerves wasn't working for some reason, so I had to uninstall/reinstall.  I don't know what that bug is, but that's not the point of this issue.

All of this would have been clearer if the nerves_bootstrap archive was versioned like hex is...

```sh
targhee:boom garth$ mix archive
* hex-0.15.0
* nerves_bootstrap
Archives installed at: /Users/garth/.mix/archives
targhee:boom garth$
```

Suggest adding a version stamp to the nerves_bootstrap archive that shows up in mix's archive list.

**Comment by mobileoverlord** [comment]
The difficult part about adding a version number to the name of the archive is that it would require our installation instructions to also have the latest version of the archive in it.

The reason that hex can do this is because they execute some logic to check which version they should pull, which happens in part because `mix local.hex` is in elixir. In our case, `mix local.nerves` is in the bootstrap archive, which doesn't help much on the initial installation.

Therefore, instead of pursuing this mechanism, I have added the information to a new mix task. `mix nerves.info` as well as from any iex session `Nerves.Bootstrap.version`

fixed in https://github.com/nerves-project/nerves/pull/75
